stages:
  - test
  - deploy

test:
  stage: test
  script: echo "Running tests"

deploy_staging:
  stage: deploy
  image: 'ruby:latest'
  type: deploy
  tags:
    - docker
  only:
    - master
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=ldssa-gs-staging --api-key=$HEROKU_STAGING_API_KEY

deploy_production:
  stage: deploy
  image: 'ruby:latest'
  type: deploy
  tags:
    - docker
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=ldssa-gs --api-key=$HEROKU_PROD_API_KEY
  when: manual
  only:
    - master