stages:
  - test
  - deploy_staging
  - deploy_production

test:
  stage: test
  script: echo "Running tests"

deploy_staging:
  image: 'ruby:latest'
  tags:
    - docker
  only:
    - master
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=ldssa-gs-staging --api-key=$HEROKU_STAGING_API_KEY

deploy_production:
  image: 
    name: wingrunr21/alpine-heroku-cli:latest
    entrypoint: ["/bin/sh"]
  variables:
    HEROKU_API_KEY: $HEROKU_PRODUCTION_API_KEY
  tags:
    - docker
  script:
    - heroku pipelines:promote --app ldssa-gs-staging -r staging
  when: manual
  only:
    - master